Avoid giving impression that it is legal to add stuff to ArborX::
arborx/ArborX pull request #462
Opened 2021-01-15 23:04 UTC by dalg24

cc @wjge

2021-01-15 23:12 UTC, dalg24 commented
cf arborx/wiki#18

2021-01-15 23:38 UTC, aprokop requested changes
Sure. If it does what you want it to, its a win. I don't think you caught all the places in ArborX doing that, though. I think DBSCAN also has this issue, for example, though in that case it's debatable.

2021-01-16 00:26 UTC, wjge commented
> cf [arborx/Wiki#18](https://github.com/arborx/Wiki/pull/18)

This gives a 404.

2021-01-16 01:34 UTC, aprokop commented
> This gives a 404.

@wjge That's because you don't have access to that private repo. Don't worry about it.

2021-01-16 03:50 UTC, dalg24 commented
DBSCAN cleanup would be more involved and can be done later

2021-01-16 03:54 UTC, aprokop commented
What about distributed tree benchmark?

2021-01-16 15:20 UTC, aprokop approved these changes

2021-01-16 15:20 UTC, merged