Modify testing queries when comparing with Boost for kNN
arborx/ArborX pull request #493
Opened 2021-03-22 16:06 UTC by aprokop

When working on trying to optimize kNN with k=1, I produced a buggy                                                                                                                                                                                                                                                                                                                      
code. However, the current version of the test never caught me. I played                                                                                                                                                                                                                                                                                                                 
around with the test, trying to find out why that was the case. While I                                                                                                                                                                                                                                                                                                                  
have not determined the root cause, I found the following:                                                                                                                                                                                                                                                                                                                               
- Using a structured grid for the tree always made the test pass                                                                                                                                                                                                                                                                                                                         
- Using a random cloud for the tree with query points being subset of                                                                                                                                                                                                                                                                                                                    
  that cloud made it pass
                                                                                                                                                                                                                                                                                                                                                                
Thus, I decided to switch to using a random cloud for source, and make                                                                                                                                                                                                                                                                                                                   
query points distinct.

2021-03-26 18:35 UTC, aprokop commented
I updated the test, building on @Rombur's work in #494. It should now be easy to plug in different data sets to run spatial and nearest comparisons with Boost.

2021-04-15 15:27 UTC, aprokop commented
OK, it's been 3 weeks and there is no explicit feedback on this PR. I am going to assume that it means that nobody cares if this gets merged or not, so I plan to merge this at the end of the day.

If you do want to provide the feedback, only critical fixes will be accepted.

2021-04-15 15:59 UTC, Rombur commented
What's going on here? You open a PR that slips through review, don't ping us on the PR for 3 weeks, and then decide on a busy week that you will merge your own PR which fails CI btw.

2021-04-15 16:00 UTC, dalg24 requested changes
I gave your oral feedback several times.  Don't have the time to elaborate now.
While they are some good changes (using a seed, reusing point cloud generations for boxes), your patch is very noisy in the sense you change a lot of things for little improvement overall.

The main blocker is you may use functions for the boiler plate bit but you must have the assertion macros own the main unit test

2021-04-15 16:09 UTC, aprokop commented
> What's going on here? You open a PR that slips through review, don't ping us on the PR for 3 weeks, and then decide on a busy week that you will merge your own PR which fails CI btw.

@Rombur Look at it from my perspective. I open PR, nothing for four days. I update the PR and explicitly ping you, nothing for 3 weeks.  I mention it several times during ArborX meetings, asking for a review, nothing. When I consider PR done, and when I pinged someone to review it, I remove it from my worklist, and don't return to it until I get the feedback. What else do you want me to do? 
And, if you looked closer, you would notice that the CI failure has nothing to do with the PR.

2021-04-15 16:12 UTC, aprokop commented
> I gave your oral feedback several times. Don't have the time to elaborate now.

@dalg24 You can think of me as having short memory, I don't always recall what feedback you gave without something to reference, like a github comment.

Thanks for the review.

> While they are some good changes (using a seed, reusing point cloud generations for boxes), your patch is very noisy in the sense you change a lot of things for little improvement overall.

That's subjective.

> The main blocker is you may use functions for the boiler plate bit but you must have the assertion macros own the main unit test

Will fix.

2021-04-15 16:42 UTC, aprokop commented
> The main blocker is you may use functions for the boiler plate bit but you must have the assertion macros own the main unit test

Actually, I'm not sure a) why you would want to do that, and b) how you propose to do that. Regarding b), we construct both boost and arborx trees and then compare the results. It's unclear to me what the function would have to return to be able to run that assert inside the test body.

2021-12-19 01:03 UTC, closed without merging