Fix warnings from hipcc
arborx/ArborX pull request #512
Opened 2021-05-04 20:26 UTC by Rombur

I am getting a bunch of warnings using rocm 4.2. hipcc wants `{}` around labels.

```
/home/users/ArborX/src/ArborX_DBSCAN.hpp:199:19: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                  labels, CorePoints{num_neigh, core_min_size}});
                  ^~~~~~ 
                  {     }
```

2021-05-04 20:28 UTC, dalg24 requested changes

2021-05-04 20:28 UTC, dalg24 commented on src/ArborX_DBSCAN.hpp
> +              Details::DBSCANCallback<MemorySpace, CorePoints>{{labels},
No, provide a constructor instead.

2021-05-04 20:36 UTC, aprokop approved these changes
Looks good to me, I did the same thing. It went unnoticed in #506 due to failing build, as I forgot to check the warnings.

2021-05-05 14:12 UTC, masterleinad approved these changes
Looks good to me.

2021-05-05 14:18 UTC, dalg24 approved these changes
I meant only a constructor for the callback but fine by me

2021-05-05 14:59 UTC, merged