[ci skip] Update CHANGELOG
arborx/ArborX pull request #762
Opened 2022-10-12 13:57 UTC by aprokop

2022-10-12 14:10 UTC, dalg24 requested changes

2022-10-12 14:10 UTC, dalg24 commented on CHANGELOG.md
> +- Migrate DBSCAN driver from `examples/` to `benchmarks/` [\#736](https://github.com/arborx/ArborX/pull/736)
Not an enhancement and we should probably add a proper example before we release

2022-10-12 14:10 UTC, dalg24 commented on CHANGELOG.md
> +- Warn about a potential loss of precision when using FDBSCAN-DenseBox [\#560](https://github.com/arborx/ArborX/pull/560)
It is more than a warning, we throw an exception

2022-10-12 14:10 UTC, dalg24 commented on CHANGELOG.md
> +- Throw an error when using the old `ArborX::Traits` interface [\#667](https://github.com/arborx/ArborX/pull/667)
We do not throw we make compilation fail via a static_assert

2022-10-18 20:29 UTC, dalg24 approved these changes

2022-10-18 20:30 UTC, dalg24 commented on CHANGELOG.md
> +- Add a DBSCAN example [\#763](https://github.com/arborx/ArborX/pull/763)
I would have merged the two

2022-10-18 22:05 UTC, aprokop commented on CHANGELOG.md
> +- Add a DBSCAN example [\#763](https://github.com/arborx/ArborX/pull/763)
I like them separately better.

2022-10-18 22:05 UTC, merged