Use Kokkos::bit_cast if available
arborx/ArborX pull request #861
Opened 2023-05-05 19:23 UTC by aprokop

2023-05-05 19:34 UTC, dalg24 requested changes

2023-05-05 19:34 UTC, dalg24 commented on src/details/ArborX_MinimumSpanningTree.hpp
> +#if KOKKOS_VERSION >= 40099
No that's too brittle that would break anyone on develop who didn't pull this morning.

2023-05-05 19:36 UTC, dalg24 commented on src/details/ArborX_MinimumSpanningTree.hpp
> +#if KOKKOS_VERSION >= 40099
OK if you use 4.1

2023-05-05 19:46 UTC, masterleinad reviewed
I am not a big fan of testing for a version still in development. I don't see a reason why we can't at least wait for the release.

2023-05-06 03:39 UTC, aprokop commented
> I am not a big fan of testing for a version still in development. I don't see a reason why we can't at least wait for the release.

We can. I wanted to add essentially a reminder so that we don't forget, but may have been too aggressive. I'm fine with either protecting by 4.1 or not doing it.

2023-05-07 13:41 UTC, dalg24 approved these changes

2023-05-08 17:19 UTC, masterleinad approved these changes

2023-05-08 17:25 UTC, merged