Use expand instead of += during scene calculation
arborx/ArborX pull request #942
Opened 2023-08-29 17:19 UTC by aprokop

This will use GeometryTraits machinery instead of relying on a specific type (Box) to provide += operator for all other geometries.

It is backwards compatible, as currently users only allowed to provide Point and Box, which are both ArborX types. So we control everything here.

The motivation here is to not provide `Box += KDOP` (as we already have an `expand` for it), as that is something one would have to do if constructing APIv2 hierarchy on KDOPs and calculating scene bounding box.

2023-08-29 17:27 UTC, dalg24 approved these changes

2023-08-29 17:29 UTC, dalg24 requested changes
Actually does `test/tstCompileOnlyTypeRequirements.cpp` not need update?

2023-08-29 17:40 UTC, aprokop commented
> Actually does `test/tstCompileOnlyTypeRequirements.cpp` not need update?

Surprisingly, it doesn't. We don't use `FakeBoundingVolume` for calculating a scene, only during the hierarchy generation, which already uses `expand`. So, we don't actually even need the `+=` member operator.

2023-08-29 18:50 UTC, dalg24 approved these changes

2023-08-29 20:20 UTC, masterleinad approved these changes

2023-08-30 03:05 UTC, aprokop commented
HIP did not start, others passed.

2023-08-30 03:05 UTC, merged